import { useState, useEffect } from 'react'
import { useSearchParams, useNavigate } from 'react-router-dom'
import { apiJson, supabase } from '../supabaseClient'
import Sidebar from '../components/Sidebar'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'

export default function ChapterLearn() {
  const [params] = useSearchParams()
  const navigate = useNavigate()
  const textbookId = params.get('textbook')
  const chapterId = params.get('chapter')
  const [chapter, setChapter] = useState(null)
  const [activeTab, setActiveTab] = useState('teaching')
  const [content, setContent] = useState('')
  const [flashcards, setFlashcards] = useState([])
  const [loading, setLoading] = useState(false)
  const [flippedCards, setFlippedCards] = useState({})

  useEffect(() => {
    if (chapterId && textbookId) {
      apiJson(`/api/textbooks/${textbookId}/chapters`).then(chs => {
        const ch = chs.find(c => c.id === chapterId)
        if (ch) setChapter(ch)
      }).catch(() => {})
    }
  }, [chapterId, textbookId])

  const generateContent = async (type) => {
    setLoading(true); setContent(''); setFlashcards([])
    try {
      const token = (await supabase.auth.getSession()).data.session?.access_token
      const res = await fetch(`${API}/api/content/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
        body: JSON.stringify({ textbook_id: textbookId, chapter_id: chapterId, content_type: type })
      })
      const data = await res.json()
      if (type === 'flashcards') setFlashcards(data.data || [])
      else setContent(data.data || 'No content generated')
    } catch { setContent('Error generating content. Try again.') }
    setLoading(false)
  }

  useEffect(() => { if (chapterId && activeTab) generateContent(activeTab) }, [activeTab, chapterId])

  const renderMd = (text) => {
    if (!text) return ''
    let h = text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    h = h.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
    h = h.replace(/\*(.+?)\*/g,'<em>$1</em>')
    h = h.replace(/^(\d+)\.\s+(.+)$/gm,'<div style="margin-left:8px;margin-bottom:6px"><strong>$1.</strong> $2</div>')
    h = h.replace(/^[-•]\s+(.+)$/gm,'<div style="margin-left:12px;margin-bottom:4px">• $1</div>')
    h = h.replace(/\n\n/g,'<br/><br/>').replace(/\n/g,'<br/>')
    return h
  }

  const downloadAsPDF = () => {
    if (!content) return
    // Create a styled HTML page and trigger print-to-PDF
    const title = `${chapter?.title || 'Chapter'} - ${activeTab === 'exam_notes' ? 'Exam Notes' : 'Summary'}`
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:'Segoe UI',sans-serif;max-width:700px;margin:40px auto;padding:20px;color:#333;line-height:1.7}
h1{color:#e8601c;font-size:22px;border-bottom:2px solid #e8601c;padding-bottom:8px}
strong{color:#1a6b3c}p{margin:8px 0}</style></head>
<body><h1>${title}</h1><div>${renderMd(content)}</div>
<p style="margin-top:30px;color:#999;font-size:12px">Generated by VidyAI — Intel AI Challenge 2026</p>
</body></html>`
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const w = window.open(url)
    setTimeout(() => { w.print(); URL.revokeObjectURL(url) }, 500)
  }

  const tabs = [
    { id: 'teaching', label: '📖 Teach Me' },
    { id: 'summary', label: '📝 Summary' },
    { id: 'exam_notes', label: '📋 Exam Notes' },
    { id: 'flashcards', label: '🃏 Flashcards' },
  ]

  return (
    <div className="app-layout"><Sidebar />
      <main className="app-content">
        <div className="mb-6 animate-fadeUp">
          <button onClick={() => navigate(-1)} className="text-sm mb-3 cursor-pointer bg-transparent border-none" style={{ color: 'var(--saffron)' }}>← Back</button>
          <h1 className="text-2xl mb-1" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>
            {chapter ? `Chapter ${chapter.chapter_number}: ${chapter.title}` : 'Loading...'}
          </h1>
          {chapter && <p className="text-sm" style={{ color: 'var(--ink3)' }}>Pages {chapter.page_start}–{chapter.page_end}</p>}
        </div>
        <div className="flex gap-2 mb-6 flex-wrap">
          {tabs.map(tab => (
            <button key={tab.id} onClick={() => setActiveTab(tab.id)}
              className="px-4 py-2.5 rounded-xl text-sm font-medium cursor-pointer border-none transition-all"
              style={{ background: activeTab === tab.id ? 'var(--ink)' : 'var(--paper2)', color: activeTab === tab.id ? 'var(--paper)' : 'var(--ink2)', fontFamily: 'var(--font-body)' }}>
              {tab.label}
            </button>
          ))}
        </div>
        <div className="flex gap-2 mb-6">
          <button onClick={() => navigate(`/ask?textbook=${textbookId}&chapter=${chapterId}`)} className="btn-main !text-[13px] !py-2">Ask AI</button>
          <button onClick={() => navigate(`/quiz?textbook=${textbookId}&chapter=${chapterId}`)} className="btn-ghost !text-[13px] !py-2">Take Quiz</button>
        </div>
        <div className="card" style={{ padding: 24, minHeight: 300 }}>
          {loading ? (
            <div className="flex items-center justify-center py-16"><div className="text-center"><div className="text-2xl mb-3 animate-spin">⟳</div><p className="text-sm" style={{ color: 'var(--ink3)' }}>Generating {activeTab}...</p></div></div>
          ) : activeTab === 'flashcards' && flashcards.length > 0 ? (
            <div className="grid gap-4" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))' }}>
              {flashcards.map((card, i) => (
                <div key={i} className="rounded-xl p-4 cursor-pointer transition-all hover:shadow-md"
                  style={{ background: flippedCards[i] ? 'var(--green-pale)' : 'var(--saffron-pale)', border: '1px solid var(--border)', minHeight: 120 }}
                  onClick={() => setFlippedCards(p => ({ ...p, [i]: !p[i] }))}>
                  <div className="text-[11px] font-semibold uppercase mb-2" style={{ color: flippedCards[i] ? 'var(--green)' : 'var(--saffron)' }}>
                    {flippedCards[i] ? 'Answer' : 'Question'} · Card {i + 1}
                  </div>
                  <div className="text-sm leading-relaxed" style={{ color: 'var(--ink)' }}>{flippedCards[i] ? card.back : card.front}</div>
                  <div className="text-[11px] mt-3" style={{ color: 'var(--ink3)' }}>Tap to {flippedCards[i] ? 'see question' : 'reveal answer'}</div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-sm leading-relaxed" style={{ color: 'var(--ink)' }} dangerouslySetInnerHTML={{ __html: renderMd(content) }} />
          )}
        </div>
        {/* Download as PDF (opens print dialog) */}
        {(activeTab === 'summary' || activeTab === 'exam_notes') && content && (
          <button className="btn-ghost !text-[13px] mt-4" onClick={downloadAsPDF}>
            📄 Download as PDF
          </button>
        )}
      </main>
    </div>
  )
}
